// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Streamers.Features.Shared.Persistance;

#nullable disable

namespace Streamers.Features.Shared.Persistance.Migrations
{
    [DbContext(typeof(StreamerDbContext))]
    [Migration("20251004173821_AddBos")]
    partial class AddBos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StreamInfoTag", b =>
                {
                    b.Property<Guid>("StreamInfosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("StreamInfosId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("StreamInfoTag", "public");
                });

            modelBuilder.Entity("StreamTag", b =>
                {
                    b.Property<Guid>("StreamsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("StreamsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("StreamTag", "public");
                });

            modelBuilder.Entity("Streamers.Features.Analytics.Models.AnalyticsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId");

                    b.ToTable("AnalyticsItems", "public");
                });

            modelBuilder.Entity("Streamers.Features.Banners.Model.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId");

                    b.ToTable("Banners", "public");
                });

            modelBuilder.Entity("Streamers.Features.Bots.Models.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("StreamVideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId");

                    b.ToTable("Bots", "public");
                });

            modelBuilder.Entity("Streamers.Features.Categories.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories", "public");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.BannedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BannedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BannedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BroadcasterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BannedById");

                    b.HasIndex("BroadcasterId");

                    b.HasIndex("UserId");

                    b.ToTable("BannedUsers", "public");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid?>("PinnedMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SettingsId")
                        .HasColumnType("uuid");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PinnedMessageId");

                    b.HasIndex("SettingsId")
                        .IsUnique();

                    b.HasIndex("StreamerId")
                        .IsUnique();

                    b.ToTable("Chats", "public");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ReplyId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ReplyId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages", "public");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.ChatSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("BannedWords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("FollowersOnly")
                        .HasColumnType("boolean");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int?>("SlowMode")
                        .HasColumnType("integer");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SubscribersOnly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId")
                        .IsUnique();

                    b.ToTable("ChatSettings", "public");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.PinnedChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("PinnedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("PinnedById");

                    b.ToTable("PinnedChatMessages", "public");
                });

            modelBuilder.Entity("Streamers.Features.Followers.Models.Follower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FollowerStreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId");

                    b.HasIndex("FollowerStreamerId", "StreamerId")
                        .IsUnique();

                    b.ToTable("Followers", "public");
                });

            modelBuilder.Entity("Streamers.Features.Notifications.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<bool>("Seen")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", "public");

                    b.HasDiscriminator().HasValue("Notification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Streamers.Features.Notifications.Models.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StreamerLive")
                        .HasColumnType("boolean");

                    b.Property<bool>("UserFollowed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId")
                        .IsUnique();

                    b.ToTable("NotificationSettings", "public");
                });

            modelBuilder.Entity("Streamers.Features.Profiles.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("ChannelBanner")
                        .HasColumnType("text");

                    b.Property<string>("Discord")
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<string>("OfflineStreamBanner")
                        .HasColumnType("text");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Youtube")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId")
                        .IsUnique();

                    b.ToTable("Profiles", "public");
                });

            modelBuilder.Entity("Streamers.Features.Roles.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BroadcasterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BroadcasterId");

                    b.HasIndex("StreamerId");

                    b.ToTable("Roles", "public");
                });

            modelBuilder.Entity("Streamers.Features.Settings.Models.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Settings", "public");
                });

            modelBuilder.Entity("Streamers.Features.StreamInfos.Models.StreamInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StreamerId")
                        .IsUnique();

                    b.ToTable("StreamInfos", "public");
                });

            modelBuilder.Entity("Streamers.Features.Streamers.Models.Streamer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentStreamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FinishedAuth")
                        .HasColumnType("boolean");

                    b.Property<long>("Followers")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasUnreadNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("SettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStreamId")
                        .IsUnique();

                    b.HasIndex("SettingId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Streamers", "public");
                });

            modelBuilder.Entity("Streamers.Features.Streams.Models.Stream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<long>("CurrentViewers")
                        .HasColumnType("bigint");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Preview")
                        .HasColumnType("text");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("StreamerId");

                    b.ToTable("Streams", "public");
                });

            modelBuilder.Entity("Streamers.Features.Streams.Models.StreamSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamKeyToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId")
                        .IsUnique();

                    b.ToTable("StreamSettings", "public");
                });

            modelBuilder.Entity("Streamers.Features.Streams.Models.StreamSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreamId");

                    b.ToTable("StreamSources", "public");
                });

            modelBuilder.Entity("Streamers.Features.SystemRoles.Models.SystemRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("RoleType")
                        .HasColumnType("integer");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId");

                    b.ToTable("SystemRoles", "public");
                });

            modelBuilder.Entity("Streamers.Features.Tags.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags", "public");
                });

            modelBuilder.Entity("Streamers.Features.Vods.Models.Vod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Preview")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StreamHls")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StreamerId");

                    b.ToTable("Vods", "public");
                });

            modelBuilder.Entity("Streamers.Features.Vods.Models.VodSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VodEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StreamerId")
                        .IsUnique();

                    b.ToTable("VodSettings", "public");
                });

            modelBuilder.Entity("TagVod", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VodsId")
                        .HasColumnType("uuid");

                    b.HasKey("TagsId", "VodsId");

                    b.HasIndex("VodsId");

                    b.ToTable("TagVod", "public");
                });

            modelBuilder.Entity("Streamers.Features.Notifications.Models.LiveStartedNotification", b =>
                {
                    b.HasBaseType("Streamers.Features.Notifications.Models.Notification");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("StreamerId");

                    b.HasDiscriminator().HasValue("LiveStartedNotification");
                });

            modelBuilder.Entity("Streamers.Features.Notifications.Models.UserFollowedNotification", b =>
                {
                    b.HasBaseType("Streamers.Features.Notifications.Models.Notification");

                    b.Property<string>("StreamerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("StreamerId");

                    b.ToTable("Notifications", "public", t =>
                        {
                            t.Property("StreamerId")
                                .HasColumnName("UserFollowedNotification_StreamerId");
                        });

                    b.HasDiscriminator().HasValue("UserFollowedNotification");
                });

            modelBuilder.Entity("StreamInfoTag", b =>
                {
                    b.HasOne("Streamers.Features.StreamInfos.Models.StreamInfo", null)
                        .WithMany()
                        .HasForeignKey("StreamInfosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Tags.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StreamTag", b =>
                {
                    b.HasOne("Streamers.Features.Streams.Models.Stream", null)
                        .WithMany()
                        .HasForeignKey("StreamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Tags.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Streamers.Features.Analytics.Models.AnalyticsItem", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Banners.Model.Banner", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Bots.Models.Bot", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.BannedUser", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "BannedBy")
                        .WithMany()
                        .HasForeignKey("BannedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Broadcaster")
                        .WithMany()
                        .HasForeignKey("BroadcasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannedBy");

                    b.Navigation("Broadcaster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.Chat", b =>
                {
                    b.HasOne("Streamers.Features.Chats.Models.PinnedChatMessage", "PinnedMessage")
                        .WithMany()
                        .HasForeignKey("PinnedMessageId");

                    b.HasOne("Streamers.Features.Chats.Models.ChatSettings", "Settings")
                        .WithOne("Chat")
                        .HasForeignKey("Streamers.Features.Chats.Models.Chat", "SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithOne("Chat")
                        .HasForeignKey("Streamers.Features.Chats.Models.Chat", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PinnedMessage");

                    b.Navigation("Settings");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.ChatMessage", b =>
                {
                    b.HasOne("Streamers.Features.Chats.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Chats.Models.ChatMessage", "Reply")
                        .WithMany()
                        .HasForeignKey("ReplyId");

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Reply");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.ChatSettings", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithOne("ChatSettings")
                        .HasForeignKey("Streamers.Features.Chats.Models.ChatSettings", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.PinnedChatMessage", b =>
                {
                    b.HasOne("Streamers.Features.Chats.Models.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "PinnedBy")
                        .WithMany()
                        .HasForeignKey("PinnedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("PinnedBy");
                });

            modelBuilder.Entity("Streamers.Features.Followers.Models.Follower", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "FollowerStreamer")
                        .WithMany()
                        .HasForeignKey("FollowerStreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FollowerStreamer");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Notifications.Models.Notification", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Streamers.Features.Notifications.Models.NotificationSettings", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithOne("NotificationSettings")
                        .HasForeignKey("Streamers.Features.Notifications.Models.NotificationSettings", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Profiles.Models.Profile", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithOne("Profile")
                        .HasForeignKey("Streamers.Features.Profiles.Models.Profile", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Roles.Models.Role", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Broadcaster")
                        .WithMany()
                        .HasForeignKey("BroadcasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broadcaster");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.StreamInfos.Models.StreamInfo", b =>
                {
                    b.HasOne("Streamers.Features.Categories.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithOne("StreamInfo")
                        .HasForeignKey("Streamers.Features.StreamInfos.Models.StreamInfo", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Streamers.Models.Streamer", b =>
                {
                    b.HasOne("Streamers.Features.Streams.Models.Stream", "CurrentStream")
                        .WithOne()
                        .HasForeignKey("Streamers.Features.Streamers.Models.Streamer", "CurrentStreamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Streamers.Features.Settings.Models.Setting", "Setting")
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentStream");

                    b.Navigation("Setting");
                });

            modelBuilder.Entity("Streamers.Features.Streams.Models.Stream", b =>
                {
                    b.HasOne("Streamers.Features.Categories.Models.Category", "Category")
                        .WithMany("Streams")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany("Streams")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Streams.Models.StreamSettings", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithOne("StreamSettings")
                        .HasForeignKey("Streamers.Features.Streams.Models.StreamSettings", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Streams.Models.StreamSource", b =>
                {
                    b.HasOne("Streamers.Features.Streams.Models.Stream", "Stream")
                        .WithMany("StreamSources")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("Streamers.Features.SystemRoles.Models.SystemRole", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany("SystemRoles")
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Vods.Models.Vod", b =>
                {
                    b.HasOne("Streamers.Features.Categories.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Vods.Models.VodSettings", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithOne("VodSettings")
                        .HasForeignKey("Streamers.Features.Vods.Models.VodSettings", "StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("TagVod", b =>
                {
                    b.HasOne("Streamers.Features.Tags.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamers.Features.Vods.Models.Vod", null)
                        .WithMany()
                        .HasForeignKey("VodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Streamers.Features.Notifications.Models.LiveStartedNotification", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Notifications.Models.UserFollowedNotification", b =>
                {
                    b.HasOne("Streamers.Features.Streamers.Models.Streamer", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("Streamers.Features.Categories.Models.Category", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Streamers.Features.Chats.Models.ChatSettings", b =>
                {
                    b.Navigation("Chat")
                        .IsRequired();
                });

            modelBuilder.Entity("Streamers.Features.Streamers.Models.Streamer", b =>
                {
                    b.Navigation("Chat")
                        .IsRequired();

                    b.Navigation("ChatSettings")
                        .IsRequired();

                    b.Navigation("NotificationSettings")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("StreamInfo")
                        .IsRequired();

                    b.Navigation("StreamSettings")
                        .IsRequired();

                    b.Navigation("Streams");

                    b.Navigation("SystemRoles");

                    b.Navigation("VodSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Streamers.Features.Streams.Models.Stream", b =>
                {
                    b.Navigation("StreamSources");
                });
#pragma warning restore 612, 618
        }
    }
}
